### ISSUE TITLE
Change Major Protocol Version to 6

### ISSUE THREAD

**Issue by brunjlar** [woofpool/cardano-private-testnet-setup#19] opened 2022-05-10 21:56 UTC
Currently, the network is started with major protocol version 5, which was the version used by Alonzo _with time handling broken_. Time handling was fixed in late 2021, bumping the protocol version to 6, which is still used now (May 2022) on both the public testnet and the Cardano mainnet.

**Comment by grzegorznowak** [comment] 2022-05-11 05:37
That's great to see you here @brunjlar , thanks for the feedback.

Indeed that's the case currently:

```
cardano-cli query protocol-parameters --testnet-magic 42 | jq '.protocolVersion.major'
5
```

For some background the crux of the setup was taken from iohk's own repo at:
https://github.com/input-output-hk/cardano-node/tree/master/scripts/byron-to-alonzo

Specifically, to get it booted directly into Alonzo:
https://github.com/input-output-hk/cardano-node/blob/master/scripts/byron-to-alonzo/mkfiles.sh

Where it lands/starts in version `5` as well.

This is where my hopefully useful throwback insight ends as I'm not sure what it would ultimately take to have that booted in the major version `6`. Do you Maybe happen to have references to some other recipes @brunjlar that do that 🤔  ?
Unless it's just a matter of swapping `5->6` which I shelf as probably to naive a solution to even try with 🤖 
 @woofpool what you think ?

**Comment by woofpool** [comment] 2022-05-11 13:47
Thanks @brunjlar for creating the issue.
I got it to use version 6 by just tweaking the shelley genesis parameters.  Fortunately, it accepted the changes.
@grzegorznowak , assigned you a PR.
[pull-request here](https://github.com/woofpool/cardano-private-testnet-setup/pull/20)

**Comment by woofpool** [comment] 2022-05-11 14:02
>Unless it's just a matter of swapping `5->6` which I shelf as probably to naive a solution to even try with robot @woofpool what you think ?
>
@grzegorznowak, I agree -- it seems naive to simply change the setting from `5` to `6`.  But, I'm assuming that the Plutus time translation fix code is activated, if the version number is `6`.  Therefore, simply tweaking the version number might do the trick.   But, I don't understand how to test the time translation to verify.

**Comment by grzegorznowak** [comment] 2022-05-11 14:04
ah yeah the simplest solutions ... 😉 

many thanks @woofpool , let me also augment the test script to include the major version checking against this particular number.

**Comment by grzegorznowak** [comment] 2022-05-11 14:18
Yes so that's done and test-confirmed to boot into the correct version. 
Ready to be merged as I see it, however (to Kurt's point) to be fully covered a test case of broken time handling, proving the current setup is immune to it, would be greatly welcomed. @brunjlar any chances you could point us the issue that tracked that ?

**Comment by woofpool** [comment] 2022-05-11 14:25
This appears to be the PR with the translate time change.
[link](https://github.com/input-output-hk/cardano-ledger/pull/2451/commits/53d2d44f760a4743c1249e058125641700e2aa25#diff-883929a31d89c9680b518514b36b3b133bbd2f21e7563b386b54f2296571efa1R195)

I'm guessing your test would have to execute a Plutus script transaction that has time based criteria, so it will be quite involved to set that up.  Maybe, we can just merge the PR with JSON tweaks as first pass?

**Comment by brunjlar** [comment] 2022-05-11 14:30
We (at GeniusYield) found it after upgrading to a newer commit of `plutus-contract`. For some reason, they're using major version 2 there... - but then we realized our private testnet tests also broke and saw that that was using version 5.

I'm afraid I also did the naive thing and just edited the genesis file from 5 to 6...

Here's a gist we used to find the problematic commit of `plutus-contract`: https://gist.github.com/brunjlar/f5bd916fdcbc04b71bb6e016819a6879

And thank you very much for acting on this so quickly! This is a very useful and great project you have here!

**Comment by grzegorznowak** [comment] 2022-05-11 14:35
@woofpool was going to propose exactly that 👍🏾 . It's an interesting challenge to be had but indeed not the one our simple integration test scripties are suited for atm.
@brunjlar great thanks ! Will use this contract to write an automated test case when we understand how 😁

**Comment by woofpool** [comment] 2022-05-11 14:46
Thanks to all for the collaboration and learning about the Plutus time changes.  Closing the issue since the changes are merged

**Closed as completed by woofpool** 2022-05-11 14:46 UTC

**Comment by grzegorznowak** [comment] 2022-05-12 11:02
Out of curiosity @brunjlar , did you have any use case where you needed to use this repository, or was just cruising through ?

Also in case you were interested in the containerized approach - which Ignacio mentioned IOHK is looking into, but I'm not sure how, if at all, you are involved in it - there's the consumer repo I've built as an aftermath, that compiles a container with private testnet in it, among other things, along with quickstart section:

https://github.com/grzegorznowak/cardano-devnet-build
